version: '3'
volumes:
  pgdata:
services:
  my-store-db:
    build: ./db
    container_name: my-store-db
    command: -c 'listen_addresses="*"'
    environment:
      - POSTGRES_USER=my_store
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=my_store_db
    restart: on-failure
    ports:
      - 25432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - store-api

networks:
  store-api:
